server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://10.248.37.3:3307/test_flyway
    username: root
    password: 123qwe
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          # options: create, create-drop, update, validate
          # create-drop: 每次加载hibernate时根据model类生成表，但是sessionFactory一关闭表就自动删除
          # update: 最常用的属性，第一次加载hibernate时根据model类会自动建立表结构，以后加载时hibernate根据model类自动更新表结构
          auto: update
  redis:
    database: 0
    host: 10.248.37.3
    port: 6379

flyway:
  # 配置Flyway要加载的SQL脚本位置
  locations: classpath:/db
